Repository PurelyBlank/Senior-Sense-Solutions, pull requests merged in 2025-04, with the labels that each got.

#11 initialize code for wearable
  project/embedded/src/wearable/heart_rate.cpp
  project/embedded/src/wearable/heart_rate.h
  project/embedded/src/wearable/wearable.ino
Labels: enhancement

#14 Add Location Page UI
  project/web/README.md
  project/web/app/biometric-monitor/page.tsx
  project/web/app/location/loader.gif
  project/web/app/location/location.css
  project/web/app/location/page.tsx
  project/web/package-lock.json
  project/web/package.json
Labels: enhancement

#15 Added endpoint for inserting wearable data to db
  project/web/backend/server.js
Labels: enhancement

#17 Darkening effect for remove patient button
  project/web/app/biometric-monitor/layout.css
  project/web/app/biometric-monitor/page.tsx
Labels: enhancement

#18 Add biometric-monitor endpoint
  project/web/app/battery-tracker/layout.tsx
  project/web/app/biometric-monitor/layout.tsx
  project/web/app/biometric-monitor/page.tsx
  project/web/app/location/layout.tsx
  project/web/app/predictive-analysis/layout.tsx
  project/web/backend/server.js
  project/web/package-lock.json
Labels: enhancement

#22 Layout
  project/web/app/(main)/battery-tracker/page.tsx
  project/web/app/(main)/biometric-monitor/homepage.css
  project/web/app/(main)/biometric-monitor/page.tsx
  project/web/app/(main)/layout.css
  project/web/app/(main)/layout.tsx
  project/web/app/(main)/location/loader.gif
  project/web/app/(main)/location/location.css
  project/web/app/(main)/location/page.tsx
  project/web/app/(main)/predictive-analysis/PrediciveAnalysis.css
  project/web/app/(main)/predictive-analysis/barChart.css
  project/web/app/(main)/predictive-analysis/barChart.tsx
  project/web/app/(main)/predictive-analysis/bloodOxygenChart.tsx
  project/web/app/(main)/predictive-analysis/heartRateChart.tsx
  project/web/app/(main)/predictive-analysis/page.tsx
  project/web/app/(main)/predictive-analysis/patientActivity.tsx
  project/web/app/(main)/predictive-analysis/patientComponent.tsx
  project/web/app/battery-tracker/layout.tsx
  project/web/app/biometric-monitor/layout.css
  project/web/app/biometric-monitor/layout.tsx
  project/web/app/location/layout.css
  project/web/app/predictive-analysis/layout.css
  project/web/app/predictive-analysis/layout.tsx
Labels: help wanted

#23 fixed lint issues with files
  project/web/app/(main)/biometric-monitor/page.tsx
  project/web/app/(main)/predictive-analysis/patientComponent.tsx
  project/web/app/layout.tsx
Labels: enhancement

#25 Add Layout Endpoint
  project/web/app/(main)/biometric-monitor/page.tsx
  project/web/app/(main)/layout.css
  project/web/app/(main)/layout.tsx
  project/web/backend/server.js
Labels: enhancement

#26 fixed predictive analysis css naming
  project/web/app/(main)/predictive-analysis/page.tsx
  project/web/app/(main)/predictive-analysis/predictiveAnalysis.css
Labels: bug, ui

#29 HeartRate endpoint
  project/web/app/(main)/biometric-monitor/HeartRateChart.tsx
  project/web/app/(main)/biometric-monitor/page.tsx
  project/web/backend/server.js
Labels: enhancement, backend

#30 Patient component dropdown menu
  project/web/app/(main)/battery-tracker/barChart.tsx
  project/web/app/(main)/battery-tracker/page.tsx
  project/web/app/(main)/biometric-monitor/homepage.css
  project/web/app/(main)/biometric-monitor/page.tsx
  project/web/app/(main)/components/patient-component/PatientComponent.css
  project/web/app/(main)/components/patient-component/PatientComponent.tsx
  project/web/app/(main)/components/patient-component/patient-dropdown.css
  project/web/app/(main)/components/patient-component/patient-dropdown.tsx
  project/web/app/(main)/predictive-analysis/page.tsx
  project/web/app/(main)/predictive-analysis/patientComponent.tsx
  project/web/app/(main)/predictive-analysis/predictiveAnalysis.css
Labels: enhancement, ui

#31 modified biometric reading guages
  project/web/app/(main)/biometric-monitor/BloodOxygenChart.tsx
  project/web/app/(main)/biometric-monitor/HeartRateChart.tsx
  project/web/app/(main)/biometric-monitor/homepage.css
Labels: ui, refactor

#36 deleted blood oxygen chart + modifed UI such that the fall chart is w…
  project/web/app/(main)/predictive-analysis/bloodOxygenChart.tsx
  project/web/app/(main)/predictive-analysis/charts.module.css
  project/web/app/(main)/predictive-analysis/fallChart.tsx
  project/web/app/(main)/predictive-analysis/page.tsx
  project/web/app/(main)/predictive-analysis/predictiveAnalysis.css
Labels: enhancement, ui, refactor

#35 Implement Add Patient Endpoint.
  project/web/app/(main)/biometric-monitor/page.tsx
  project/web/app/(main)/components/patient-component/PatientComponent.css
  project/web/app/(main)/components/patient-component/PatientComponent.tsx
  project/web/backend/server.js
Labels: enhancement, ui, backend
